=== Sri-Aurobindo/Web-Application-Using-MERN/clubServer/test/jsonSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://locolhost:9060/activities",
    "title": "Activity Schema",
    "description": "A Schema that requires a JSON object",
    "type": "object",
    "properties":
        {
            "Name": {
            "description": "the Name of the activity",
            "type": "string",
            "minLength": 1,
            "maxLength": 40
            },
            "Date": {
            "description": "the date of the activity",
            "type": "string"
            },
            "Time":{
            "description": "the Time of the activity",
            "type": "string",
            "minLength": 1,
            "maxLength": 15
            },
            "Description":{
            "description": "the summary of the activity",
            "type": "string",
            "minLength": 1,
            "maxLength": 100
            }
        },
        "required": ["Name", "Date"],
        "additionalProperties": true
  }

=== Sri-Aurobindo/Web-Application-Using-MERN/clubServer/eventData.json
[{"Name":"Daily Soccer Teaching Session",
    "Date":"Everyday except Weekends",
    "Time":"6.00 AM",
    "Description":"Soccer Sessions"},
    {"Name":"5 VS 5 Men Soccer Match",
    "Date":"09/10/2021",
    "Time":"10.30 AM",
    "Description":"Interclub 5 vs 5 match"},
    {"Name":"Match 26 (HOME VS AWAY)",
    "Date":"09/12/2021",
    "Time":"1.30 PM",
    "Description":"Gotham Pro Legue"},
    {"Name":"7 VS 7 Women Half Ground Soccer Match",
    "Date":"09/13/2021",
    "Time":"4.30 PM",
    "Description":"Interclub Practice Match"}
    ]
